### ISSUE TITLE
A question about lstm.py

### ISSUE THREAD

**Issue by 333caowei** [thtrieu/qclass_dl#1]
Hi thtrieu:
    Your repository is pretty cool and easy to read. But I have a few  questions. 

```
# Collect the appropriate last words into variable output (dimension = batch x embedding_size)
        output = outputs[0]
        one = tf.ones([1, hidden_unit], tf.float32)
        with tf.variable_scope("Output"):
            tf.get_variable_scope().reuse_variables()
            for i in range(1,len(outputs)):
                ind = self.real_len < (i+1)
                ind = tf.to_float(ind)
                ind = tf.expand_dims(ind, -1)
                mat = tf.matmul(ind, one)
                output = tf.add(tf.mul(output, mat),tf.mul(outputs[i], 1.0 - mat))
```

I am not sure why you do these step. Can you explain some detail about it please?

By the way, when I try to remove these lines, just use `output = outputs[-1]`, I get terrible result. I guess  `output = outputs[-1]` my be the output of  `<PAD/>` word.  So my result is terrible. Am I right?

**Comment by thtrieu** [comment]
Hi @333caowei , so cool someone actually looked into my code. Short answer is: yes your guess is correct. Long answer is: I actually wrote a blog post for this exact piece of code, you can read it [here](http://thtrieu.github.io/posts/python-tensorflow-catching-the-last-output/) .

**Comment by 333caowei** [comment]
@thtrieu HAHA, thank you so much!
